//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34209
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Original file name:
// Generation date: 7/6/2015 6:49:22 AM
namespace LightSwitchApplication.Implementation
{
    
    /// <summary>
    /// There are no comments for ApplicationData in the schema.
    /// </summary>
    public partial class ApplicationData : global::Microsoft.LightSwitch.ClientGenerated.Implementation.DataServiceContext
    {
        /// <summary>
        /// Initialize a new ApplicationData object.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public ApplicationData(global::System.Uri serviceRoot) : 
                base(serviceRoot, global::System.Data.Services.Common.DataServiceProtocolVersion.V3)
        {
            this.ResolveName = new global::System.Func<global::System.Type, string>(this.ResolveNameFromType);
            this.ResolveType = new global::System.Func<string, global::System.Type>(this.ResolveTypeFromName);
            this.OnContextCreated();
            this.Format.LoadServiceModel = GeneratedEdmModel.GetInstance;
        }
        partial void OnContextCreated();
        /// <summary>
        /// Since the namespace configured for this service reference
        /// in Visual Studio is different from the one indicated in the
        /// server schema, use type-mappers to map between the two.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        protected global::System.Type ResolveTypeFromName(string typeName)
        {
            global::System.Type resolvedType = this.DefaultResolveType(typeName, "LightSwitchApplication", "LightSwitchApplication.Implementation");
            if ((resolvedType != null))
            {
                return resolvedType;
            }
            return null;
        }
        /// <summary>
        /// Since the namespace configured for this service reference
        /// in Visual Studio is different from the one indicated in the
        /// server schema, use type-mappers to map between the two.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        protected string ResolveNameFromType(global::System.Type clientType)
        {
            if (clientType.Namespace.Equals("LightSwitchApplication.Implementation", global::System.StringComparison.Ordinal))
            {
                return string.Concat("LightSwitchApplication.", clientType.Name);
            }
            return null;
        }
        /// <summary>
        /// There are no comments for Customers in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public global::System.Data.Services.Client.DataServiceQuery<Customer> Customers
        {
            get
            {
                if ((this._Customers == null))
                {
                    this._Customers = base.CreateQuery<Customer>("Customers");
                }
                return this._Customers;
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private global::System.Data.Services.Client.DataServiceQuery<Customer> _Customers;
        /// <summary>
        /// There are no comments for InvoiceDetails in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public global::System.Data.Services.Client.DataServiceQuery<InvoiceDetail> InvoiceDetails
        {
            get
            {
                if ((this._InvoiceDetails == null))
                {
                    this._InvoiceDetails = base.CreateQuery<InvoiceDetail>("InvoiceDetails");
                }
                return this._InvoiceDetails;
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private global::System.Data.Services.Client.DataServiceQuery<InvoiceDetail> _InvoiceDetails;
        /// <summary>
        /// There are no comments for Invoices in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public global::System.Data.Services.Client.DataServiceQuery<Invoice> Invoices
        {
            get
            {
                if ((this._Invoices == null))
                {
                    this._Invoices = base.CreateQuery<Invoice>("Invoices");
                }
                return this._Invoices;
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private global::System.Data.Services.Client.DataServiceQuery<Invoice> _Invoices;
        /// <summary>
        /// There are no comments for Storages in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public global::System.Data.Services.Client.DataServiceQuery<Storage> Storages
        {
            get
            {
                if ((this._Storages == null))
                {
                    this._Storages = base.CreateQuery<Storage>("Storages");
                }
                return this._Storages;
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private global::System.Data.Services.Client.DataServiceQuery<Storage> _Storages;
        /// <summary>
        /// There are no comments for Customers in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public void AddToCustomers(Customer customer)
        {
            base.AddObject("Customers", customer);
        }
        /// <summary>
        /// There are no comments for InvoiceDetails in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public void AddToInvoiceDetails(InvoiceDetail invoiceDetail)
        {
            base.AddObject("InvoiceDetails", invoiceDetail);
        }
        /// <summary>
        /// There are no comments for Invoices in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public void AddToInvoices(Invoice invoice)
        {
            base.AddObject("Invoices", invoice);
        }
        /// <summary>
        /// There are no comments for Storages in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public void AddToStorages(Storage storage)
        {
            base.AddObject("Storages", storage);
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private abstract class GeneratedEdmModel
        {
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
            private static global::Microsoft.Data.Edm.IEdmModel ParsedModel = LoadModelFromString();
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
            private const string ModelPart0 = "<edmx:Edmx Version=\"1.0\" xmlns:edmx=\"http://schemas.microsoft.com/ado/2007/06/edm" +
                "x\"><edmx:DataServices xmlns:m=\"http://schemas.microsoft.com/ado/2007/08/dataserv" +
                "ices/metadata\" m:DataServiceVersion=\"1.0\" m:MaxDataServiceVersion=\"3.0\"><Schema " +
                "xmlns:annotation=\"http://schemas.microsoft.com/ado/2009/02/edm/annotation\" Names" +
                "pace=\"LightSwitchApplication\" Alias=\"Self\" xmlns=\"http://schemas.microsoft.com/a" +
                "do/2008/09/edm\"><EntityType Name=\"Customer\"><Key><PropertyRef Name=\"Id\" /></Key>" +
                "<Property Name=\"Id\" Type=\"Edm.Int32\" Nullable=\"false\" annotation:StoreGeneratedP" +
                "attern=\"Identity\" /><Property Name=\"Name\" Type=\"Edm.String\" Nullable=\"false\" Max" +
                "Length=\"255\" /><Property Name=\"Phone\" Type=\"Edm.String\" MaxLength=\"255\" /><Prope" +
                "rty Name=\"Address\" Type=\"Edm.String\" MaxLength=\"255\" /><Property Name=\"CreatedBy" +
                "\" Type=\"Edm.String\" MaxLength=\"255\" /><Property Name=\"Created\" Type=\"Edm.DateTim" +
                "eOffset\" /><Property Name=\"ModifiedBy\" Type=\"Edm.String\" MaxLength=\"255\" /><Prop" +
                "erty Name=\"Modified\" Type=\"Edm.DateTimeOffset\" /><Property Name=\"RowVersion\" Typ" +
                "e=\"Edm.Binary\" Nullable=\"false\" ConcurrencyMode=\"Fixed\" annotation:StoreGenerate" +
                "dPattern=\"Computed\" /><NavigationProperty Name=\"Invoices\" Relationship=\"LightSwi" +
                "tchApplication.Customer_Invoice\" ToRole=\"Invoice\" FromRole=\"Customer\" /><Navigat" +
                "ionProperty Name=\"Storages\" Relationship=\"LightSwitchApplication.Customer_Storag" +
                "e\" ToRole=\"Storage\" FromRole=\"Customer\" /></EntityType><EntityType Name=\"Invoice" +
                "Detail\"><Key><PropertyRef Name=\"Id\" /></Key><Property Name=\"Id\" Type=\"Edm.Int32\"" +
                " Nullable=\"false\" annotation:StoreGeneratedPattern=\"Identity\" /><Property Name=\"" +
                "Comments\" Type=\"Edm.String\" MaxLength=\"255\" /><Property Name=\"InvoiceDetail_Invo" +
                "ice\" Type=\"Edm.Int32\" Nullable=\"false\" /><Property Name=\"AmountDue\" Type=\"Edm.De" +
                "cimal\" Precision=\"18\" Scale=\"2\" /><Property Name=\"CreatedBy\" Type=\"Edm.String\" M" +
                "axLength=\"255\" /><Property Name=\"Created\" Type=\"Edm.DateTimeOffset\" /><Property " +
                "Name=\"ModifiedBy\" Type=\"Edm.String\" MaxLength=\"255\" /><Property Name=\"Modified\" " +
                "Type=\"Edm.DateTimeOffset\" /><Property Name=\"RowVersion\" Type=\"Edm.Binary\" Nullab" +
                "le=\"false\" ConcurrencyMode=\"Fixed\" annotation:StoreGeneratedPattern=\"Computed\" /" +
                "><NavigationProperty Name=\"Invoice\" Relationship=\"LightSwitchApplication.Invoice" +
                "Detail_Invoice\" ToRole=\"Invoice\" FromRole=\"InvoiceDetail\" /></EntityType><Entity" +
                "Type Name=\"Invoice\"><Key><PropertyRef Name=\"Id\" /></Key><Property Name=\"Id\" Type" +
                "=\"Edm.Int32\" Nullable=\"false\" annotation:StoreGeneratedPattern=\"Identity\" /><Pro" +
                "perty Name=\"InvoiceDate\" Type=\"Edm.DateTime\" Nullable=\"false\" /><Property Name=\"" +
                "InvoiceID\" Type=\"Edm.String\" MaxLength=\"255\" /><Property Name=\"IsActive\" Type=\"E" +
                "dm.Binary\" MaxLength=\"Max\" /><Property Name=\"Customer_Invoice\" Type=\"Edm.Int32\" " +
                "Nullable=\"false\" /><Property Name=\"CreatedBy\" Type=\"Edm.String\" MaxLength=\"255\" " +
                "/><Property Name=\"Created\" Type=\"Edm.DateTimeOffset\" /><Property Name=\"ModifiedB" +
                "y\" Type=\"Edm.String\" MaxLength=\"255\" /><Property Name=\"Modified\" Type=\"Edm.DateT" +
                "imeOffset\" /><Property Name=\"RowVersion\" Type=\"Edm.Binary\" Nullable=\"false\" Conc" +
                "urrencyMode=\"Fixed\" annotation:StoreGeneratedPattern=\"Computed\" /><NavigationPro" +
                "perty Name=\"InvoiceDetails\" Relationship=\"LightSwitchApplication.InvoiceDetail_I" +
                "nvoice\" ToRole=\"InvoiceDetail\" FromRole=\"Invoice\" /><NavigationProperty Name=\"Cu" +
                "stomer\" Relationship=\"LightSwitchApplication.Customer_Invoice\" ToRole=\"Customer\"" +
                " FromRole=\"Invoice\" /></EntityType><EntityType Name=\"Storage\"><Key><PropertyRef " +
                "Name=\"Id\" /></Key><Property Name=\"Id\" Type=\"Edm.Int32\" Nullable=\"false\" annotati" +
                "on:StoreGeneratedPattern=\"Identity\" /><Property Name=\"StorageNumber\" Type=\"Edm.S" +
                "tring\" Nullable=\"false\" MaxLength=\"255\" /><Property Name=\"Price\" Type=\"Edm.Decim" +
                "al\" Nullable=\"false\" Precision=\"18\" Scale=\"2\" /><Property Name=\"Customer_Storage" +
                "\" Type=\"Edm.Int32\" Nullable=\"false\" /><Property Name=\"CreatedBy\" Type=\"Edm.Strin" +
                "g\" MaxLength=\"255\" /><Property Name=\"Created\" Type=\"Edm.DateTimeOffset\" /><Prope" +
                "rty Name=\"ModifiedBy\" Type=\"Edm.String\" MaxLength=\"255\" /><Property Name=\"Modifi" +
                "ed\" Type=\"Edm.DateTimeOffset\" /><Property Name=\"RowVersion\" Type=\"Edm.Binary\" Nu" +
                "llable=\"false\" ConcurrencyMode=\"Fixed\" annotation:StoreGeneratedPattern=\"Compute" +
                "d\" /><NavigationProperty Name=\"Customer\" Relationship=\"LightSwitchApplication.Cu" +
                "stomer_Storage\" ToRole=\"Customer\" FromRole=\"Storage\" /></EntityType><Association" +
                " Name=\"Customer_Invoice\"><End Role=\"Customer\" Type=\"LightSwitchApplication.Custo" +
                "mer\" Multiplicity=\"1\" /><End Role=\"Invoice\" Type=\"LightSwitchApplication.Invoice" +
                "\" Multiplicity=\"*\" /><ReferentialConstraint><Principal Role=\"Customer\"><Property" +
                "Ref Name=\"Id\" /></Principal><Dependent Role=\"Invoice\"><PropertyRef Name=\"Custome" +
                "r_Invoice\" /></Dependent></ReferentialConstraint></Association><Association Name" +
                "=\"Customer_Storage\"><End Role=\"Customer\" Type=\"LightSwitchApplication.Customer\" " +
                "Multiplicity=\"1\" /><End Role=\"Storage\" Type=\"LightSwitchApplication.Storage\" Mul" +
                "tiplicity=\"*\" /><ReferentialConstraint><Principal Role=\"Customer\"><PropertyRef N" +
                "ame=\"Id\" /></Principal><Dependent Role=\"Storage\"><PropertyRef Name=\"Customer_Sto" +
                "rage\" /></Dependent></ReferentialConstraint></Association><Association Name=\"Inv" +
                "oiceDetail_Invoice\"><End Role=\"Invoice\" Type=\"LightSwitchApplication.Invoice\" Mu" +
                "ltiplicity=\"1\" /><End Role=\"InvoiceDetail\" Type=\"LightSwitchApplication.InvoiceD" +
                "etail\" Multiplicity=\"*\" /><ReferentialConstraint><Principal Role=\"Invoice\"><Prop" +
                "ertyRef Name=\"Id\" /></Principal><Dependent Role=\"InvoiceDetail\"><PropertyRef Nam" +
                "e=\"InvoiceDetail_Invoice\" /></Dependent></ReferentialConstraint></Association><E" +
                "ntityContainer Name=\"ApplicationData\" m:IsDefaultEntityContainer=\"true\"><EntityS" +
                "et Name=\"Customers\" EntityType=\"LightSwitchApplication.Customer\" /><EntitySet Na" +
                "me=\"InvoiceDetails\" EntityType=\"LightSwitchApplication.InvoiceDetail\" /><EntityS" +
                "et Name=\"Invoices\" EntityType=\"LightSwitchApplication.Invoice\" /><EntitySet Name" +
                "=\"Storages\" EntityType=\"LightSwitchApplication.Storage\" /><AssociationSet Name=\"" +
                "Customer_Invoice\" Association=\"LightSwitchApplication.Customer_Invoice\"><End Rol" +
                "e=\"Customer\" EntitySet=\"Customers\" /><End Role=\"Invoice\" EntitySet=\"Invoices\" />" +
                "</AssociationSet><AssociationSet Name=\"Customer_Storage\" Association=\"LightSwitc" +
                "hApplication.Customer_Storage\"><End Role=\"Customer\" EntitySet=\"Customers\" /><End" +
                " Role=\"Storage\" EntitySet=\"Storages\" /></AssociationSet><AssociationSet Name=\"In" +
                "voiceDetail_Invoice\" Association=\"LightSwitchApplication.InvoiceDetail_Invoice\">" +
                "<End Role=\"Invoice\" EntitySet=\"Invoices\" /><End Role=\"InvoiceDetail\" EntitySet=\"" +
                "InvoiceDetails\" /></AssociationSet><FunctionImport Name=\"Microsoft_LightSwitch_G" +
                "etCanInformation\" ReturnType=\"Edm.String\" m:HttpMethod=\"GET\"><Parameter Name=\"da" +
                "taServiceMembers\" Type=\"Edm.String\" Mode=\"In\" /></FunctionImport></EntityContain" +
                "er></Schema></edmx:DataServices></edmx:Edmx>";
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
            private static string GetConcatenatedEdmxString()
            {
                return string.Concat(ModelPart0);
            }
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
            public static global::Microsoft.Data.Edm.IEdmModel GetInstance()
            {
                return ParsedModel;
            }
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
            private static global::Microsoft.Data.Edm.IEdmModel LoadModelFromString()
            {
                string edmxToParse = GetConcatenatedEdmxString();
                global::System.Xml.XmlReader reader = CreateXmlReader(edmxToParse);
                try
                {
                    return global::Microsoft.Data.Edm.Csdl.EdmxReader.Parse(reader);
                }
                finally
                {
                    ((global::System.IDisposable)(reader)).Dispose();
                }
            }
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
            private static global::System.Xml.XmlReader CreateXmlReader(string edmxToParse)
            {
                return global::System.Xml.XmlReader.Create(new global::System.IO.StringReader(edmxToParse));
            }
        }
    }
    /// <summary>
    /// There are no comments for LightSwitchApplication.Customer in the schema.
    /// </summary>
    /// <KeyProperties>
    /// Id
    /// </KeyProperties>
    [global::System.Data.Services.Common.EntitySetAttribute("Customers")]
    [global::System.Data.Services.Common.DataServiceKeyAttribute("Id")]
    public partial class Customer : global::Microsoft.LightSwitch.ClientGenerated.Implementation.EntityBase, global::System.ComponentModel.INotifyPropertyChanged
    {
        /// <summary>
        /// Create a new Customer object.
        /// </summary>
        /// <param name="ID">Initial value of Id.</param>
        /// <param name="name">Initial value of Name.</param>
        /// <param name="rowVersion">Initial value of RowVersion.</param>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public static Customer CreateCustomer(int ID, string name, byte[] rowVersion)
        {
            Customer customer = new Customer();
            customer.Id = ID;
            customer.Name = name;
            customer.RowVersion = rowVersion;
            return customer;
        }
        /// <summary>
        /// There are no comments for Property Id in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public int Id
        {
            get
            {
                return this._Id;
            }
            set
            {
                this.OnIdChanging(value);
                if (object.Equals(this.Id, value))
                {
                    return;
                }
                this._Id = value;
                this.OnIdChanged();
                this.OnPropertyChanged("Id");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private int _Id;
        partial void OnIdChanging(int value);
        partial void OnIdChanged();
        /// <summary>
        /// There are no comments for Property Name in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public string Name
        {
            get
            {
                return this._Name;
            }
            set
            {
                this.OnNameChanging(value);
                if (object.Equals(this.Name, value))
                {
                    return;
                }
                this._Name = value;
                this.OnNameChanged();
                this.OnPropertyChanged("Name");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private string _Name;
        partial void OnNameChanging(string value);
        partial void OnNameChanged();
        /// <summary>
        /// There are no comments for Property Phone in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public string Phone
        {
            get
            {
                return this._Phone;
            }
            set
            {
                this.OnPhoneChanging(value);
                if (object.Equals(this.Phone, value))
                {
                    return;
                }
                this._Phone = value;
                this.OnPhoneChanged();
                this.OnPropertyChanged("Phone");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private string _Phone;
        partial void OnPhoneChanging(string value);
        partial void OnPhoneChanged();
        /// <summary>
        /// There are no comments for Property Address in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public string Address
        {
            get
            {
                return this._Address;
            }
            set
            {
                this.OnAddressChanging(value);
                if (object.Equals(this.Address, value))
                {
                    return;
                }
                this._Address = value;
                this.OnAddressChanged();
                this.OnPropertyChanged("Address");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private string _Address;
        partial void OnAddressChanging(string value);
        partial void OnAddressChanged();
        /// <summary>
        /// There are no comments for Property CreatedBy in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public string CreatedBy
        {
            get
            {
                return this._CreatedBy;
            }
            set
            {
                this.OnCreatedByChanging(value);
                if (object.Equals(this.CreatedBy, value))
                {
                    return;
                }
                this._CreatedBy = value;
                this.OnCreatedByChanged();
                this.OnPropertyChanged("CreatedBy");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private string _CreatedBy;
        partial void OnCreatedByChanging(string value);
        partial void OnCreatedByChanged();
        /// <summary>
        /// There are no comments for Property Created in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public global::System.Nullable<global::System.DateTimeOffset> Created
        {
            get
            {
                return this._Created;
            }
            set
            {
                this.OnCreatedChanging(value);
                if (object.Equals(this.Created, value))
                {
                    return;
                }
                this._Created = value;
                this.OnCreatedChanged();
                this.OnPropertyChanged("Created");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private global::System.Nullable<global::System.DateTimeOffset> _Created;
        partial void OnCreatedChanging(global::System.Nullable<global::System.DateTimeOffset> value);
        partial void OnCreatedChanged();
        /// <summary>
        /// There are no comments for Property ModifiedBy in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public string ModifiedBy
        {
            get
            {
                return this._ModifiedBy;
            }
            set
            {
                this.OnModifiedByChanging(value);
                if (object.Equals(this.ModifiedBy, value))
                {
                    return;
                }
                this._ModifiedBy = value;
                this.OnModifiedByChanged();
                this.OnPropertyChanged("ModifiedBy");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private string _ModifiedBy;
        partial void OnModifiedByChanging(string value);
        partial void OnModifiedByChanged();
        /// <summary>
        /// There are no comments for Property Modified in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public global::System.Nullable<global::System.DateTimeOffset> Modified
        {
            get
            {
                return this._Modified;
            }
            set
            {
                this.OnModifiedChanging(value);
                if (object.Equals(this.Modified, value))
                {
                    return;
                }
                this._Modified = value;
                this.OnModifiedChanged();
                this.OnPropertyChanged("Modified");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private global::System.Nullable<global::System.DateTimeOffset> _Modified;
        partial void OnModifiedChanging(global::System.Nullable<global::System.DateTimeOffset> value);
        partial void OnModifiedChanged();
        /// <summary>
        /// There are no comments for Property RowVersion in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public byte[] RowVersion
        {
            get
            {
                if ((this._RowVersion != null))
                {
                    return ((byte[])(this._RowVersion.Clone()));
                }
                else
                {
                    return null;
                }
            }
            set
            {
                this.OnRowVersionChanging(value);
                if (object.Equals(this.RowVersion, value))
                {
                    return;
                }
                this._RowVersion = value;
                this.OnRowVersionChanged();
                this.OnPropertyChanged("RowVersion");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private byte[] _RowVersion;
        partial void OnRowVersionChanging(byte[] value);
        partial void OnRowVersionChanged();
        /// <summary>
        /// There are no comments for Invoices in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public global::System.Data.Services.Client.DataServiceCollection<Invoice> Invoices
        {
            get
            {
                this.@__Invoices.EnsureValueInitialized();
                return this._Invoices;
            }
            set
            {
                this._Invoices = value;
                this.OnPropertyChanged("Invoices");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private global::System.Data.Services.Client.DataServiceCollection<Invoice> _Invoices = new global::System.Data.Services.Client.DataServiceCollection<Invoice>(null, global::System.Data.Services.Client.TrackingMode.None);
        /// <summary>
        /// There are no comments for Storages in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public global::System.Data.Services.Client.DataServiceCollection<Storage> Storages
        {
            get
            {
                this.@__Storages.EnsureValueInitialized();
                return this._Storages;
            }
            set
            {
                this._Storages = value;
                this.OnPropertyChanged("Storages");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private global::System.Data.Services.Client.DataServiceCollection<Storage> _Storages = new global::System.Data.Services.Client.DataServiceCollection<Storage>(null, global::System.Data.Services.Client.TrackingMode.None);
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public event global::System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        protected virtual void OnPropertyChanged(string property)
        {
            if ((this.PropertyChanged != null))
            {
                this.PropertyChanged(this, new global::System.ComponentModel.PropertyChangedEventArgs(property));
            }
        }
    }
    /// <summary>
    /// There are no comments for LightSwitchApplication.InvoiceDetail in the schema.
    /// </summary>
    /// <KeyProperties>
    /// Id
    /// </KeyProperties>
    [global::System.Data.Services.Common.EntitySetAttribute("InvoiceDetails")]
    [global::System.Data.Services.Common.DataServiceKeyAttribute("Id")]
    public partial class InvoiceDetail : global::Microsoft.LightSwitch.ClientGenerated.Implementation.EntityBase, global::System.ComponentModel.INotifyPropertyChanged
    {
        /// <summary>
        /// Create a new InvoiceDetail object.
        /// </summary>
        /// <param name="ID">Initial value of Id.</param>
        /// <param name="invoiceDetail_Invoice">Initial value of InvoiceDetail_Invoice.</param>
        /// <param name="rowVersion">Initial value of RowVersion.</param>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public static InvoiceDetail CreateInvoiceDetail(int ID, int invoiceDetail_Invoice, byte[] rowVersion)
        {
            InvoiceDetail invoiceDetail = new InvoiceDetail();
            invoiceDetail.Id = ID;
            invoiceDetail.InvoiceDetail_Invoice = invoiceDetail_Invoice;
            invoiceDetail.RowVersion = rowVersion;
            return invoiceDetail;
        }
        /// <summary>
        /// There are no comments for Property Id in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public int Id
        {
            get
            {
                return this._Id;
            }
            set
            {
                this.OnIdChanging(value);
                if (object.Equals(this.Id, value))
                {
                    return;
                }
                this._Id = value;
                this.OnIdChanged();
                this.OnPropertyChanged("Id");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private int _Id;
        partial void OnIdChanging(int value);
        partial void OnIdChanged();
        /// <summary>
        /// There are no comments for Property Comments in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public string Comments
        {
            get
            {
                return this._Comments;
            }
            set
            {
                this.OnCommentsChanging(value);
                if (object.Equals(this.Comments, value))
                {
                    return;
                }
                this._Comments = value;
                this.OnCommentsChanged();
                this.OnPropertyChanged("Comments");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private string _Comments;
        partial void OnCommentsChanging(string value);
        partial void OnCommentsChanged();
        /// <summary>
        /// There are no comments for Property InvoiceDetail_Invoice in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public int InvoiceDetail_Invoice
        {
            get
            {
                return this._InvoiceDetail_Invoice;
            }
            set
            {
                this.OnInvoiceDetail_InvoiceChanging(value);
                if (object.Equals(this.InvoiceDetail_Invoice, value))
                {
                    return;
                }
                this._InvoiceDetail_Invoice = value;
                this.OnInvoiceDetail_InvoiceChanged();
                this.OnPropertyChanged("InvoiceDetail_Invoice");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private int _InvoiceDetail_Invoice;
        partial void OnInvoiceDetail_InvoiceChanging(int value);
        partial void OnInvoiceDetail_InvoiceChanged();
        /// <summary>
        /// There are no comments for Property AmountDue in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public global::System.Nullable<decimal> AmountDue
        {
            get
            {
                return this._AmountDue;
            }
            set
            {
                this.OnAmountDueChanging(value);
                if (object.Equals(this.AmountDue, value))
                {
                    return;
                }
                this._AmountDue = value;
                this.OnAmountDueChanged();
                this.OnPropertyChanged("AmountDue");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private global::System.Nullable<decimal> _AmountDue;
        partial void OnAmountDueChanging(global::System.Nullable<decimal> value);
        partial void OnAmountDueChanged();
        /// <summary>
        /// There are no comments for Property CreatedBy in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public string CreatedBy
        {
            get
            {
                return this._CreatedBy;
            }
            set
            {
                this.OnCreatedByChanging(value);
                if (object.Equals(this.CreatedBy, value))
                {
                    return;
                }
                this._CreatedBy = value;
                this.OnCreatedByChanged();
                this.OnPropertyChanged("CreatedBy");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private string _CreatedBy;
        partial void OnCreatedByChanging(string value);
        partial void OnCreatedByChanged();
        /// <summary>
        /// There are no comments for Property Created in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public global::System.Nullable<global::System.DateTimeOffset> Created
        {
            get
            {
                return this._Created;
            }
            set
            {
                this.OnCreatedChanging(value);
                if (object.Equals(this.Created, value))
                {
                    return;
                }
                this._Created = value;
                this.OnCreatedChanged();
                this.OnPropertyChanged("Created");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private global::System.Nullable<global::System.DateTimeOffset> _Created;
        partial void OnCreatedChanging(global::System.Nullable<global::System.DateTimeOffset> value);
        partial void OnCreatedChanged();
        /// <summary>
        /// There are no comments for Property ModifiedBy in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public string ModifiedBy
        {
            get
            {
                return this._ModifiedBy;
            }
            set
            {
                this.OnModifiedByChanging(value);
                if (object.Equals(this.ModifiedBy, value))
                {
                    return;
                }
                this._ModifiedBy = value;
                this.OnModifiedByChanged();
                this.OnPropertyChanged("ModifiedBy");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private string _ModifiedBy;
        partial void OnModifiedByChanging(string value);
        partial void OnModifiedByChanged();
        /// <summary>
        /// There are no comments for Property Modified in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public global::System.Nullable<global::System.DateTimeOffset> Modified
        {
            get
            {
                return this._Modified;
            }
            set
            {
                this.OnModifiedChanging(value);
                if (object.Equals(this.Modified, value))
                {
                    return;
                }
                this._Modified = value;
                this.OnModifiedChanged();
                this.OnPropertyChanged("Modified");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private global::System.Nullable<global::System.DateTimeOffset> _Modified;
        partial void OnModifiedChanging(global::System.Nullable<global::System.DateTimeOffset> value);
        partial void OnModifiedChanged();
        /// <summary>
        /// There are no comments for Property RowVersion in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public byte[] RowVersion
        {
            get
            {
                if ((this._RowVersion != null))
                {
                    return ((byte[])(this._RowVersion.Clone()));
                }
                else
                {
                    return null;
                }
            }
            set
            {
                this.OnRowVersionChanging(value);
                if (object.Equals(this.RowVersion, value))
                {
                    return;
                }
                this._RowVersion = value;
                this.OnRowVersionChanged();
                this.OnPropertyChanged("RowVersion");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private byte[] _RowVersion;
        partial void OnRowVersionChanging(byte[] value);
        partial void OnRowVersionChanged();
        /// <summary>
        /// There are no comments for Invoice in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public Invoice Invoice
        {
            get
            {
                this.@__Invoice.EnsureValueInitialized();
                return this._Invoice;
            }
            set
            {
                Invoice previous = this.Invoice;
                if ((previous == value))
                {
                    return;
                }
                if ((previous != null))
                {
                    this._Invoice = null;
                    this.@__Invoice.OnValueSet();
                    previous.InvoiceDetails.Remove(this);
                }
                if ((this.___Host != null))
                {
                    if ((value != null))
                    {
                        this.InvoiceDetail_Invoice = value.Id;
                    }
                    else
                    {
                        this.InvoiceDetail_Invoice = default(int);
                    }
                }
                this._Invoice = value;
                this.@__Invoice.OnValueSet();
                if ((value != null))
                {
                    value.@__InvoiceDetails.Add(this);
                }
                this.___OnPropertyChanged("Invoice");
                this.OnPropertyChanged("Invoice");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private Invoice _Invoice;
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public event global::System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        protected virtual void OnPropertyChanged(string property)
        {
            if ((this.PropertyChanged != null))
            {
                this.PropertyChanged(this, new global::System.ComponentModel.PropertyChangedEventArgs(property));
            }
        }
    }
    /// <summary>
    /// There are no comments for LightSwitchApplication.Invoice in the schema.
    /// </summary>
    /// <KeyProperties>
    /// Id
    /// </KeyProperties>
    [global::System.Data.Services.Common.EntitySetAttribute("Invoices")]
    [global::System.Data.Services.Common.DataServiceKeyAttribute("Id")]
    public partial class Invoice : global::Microsoft.LightSwitch.ClientGenerated.Implementation.EntityBase, global::System.ComponentModel.INotifyPropertyChanged
    {
        /// <summary>
        /// Create a new Invoice object.
        /// </summary>
        /// <param name="ID">Initial value of Id.</param>
        /// <param name="invoiceDate">Initial value of InvoiceDate.</param>
        /// <param name="customer_Invoice">Initial value of Customer_Invoice.</param>
        /// <param name="rowVersion">Initial value of RowVersion.</param>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public static Invoice CreateInvoice(int ID, global::System.DateTime invoiceDate, int customer_Invoice, byte[] rowVersion)
        {
            Invoice invoice = new Invoice();
            invoice.Id = ID;
            invoice.InvoiceDate = invoiceDate;
            invoice.Customer_Invoice = customer_Invoice;
            invoice.RowVersion = rowVersion;
            return invoice;
        }
        /// <summary>
        /// There are no comments for Property Id in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public int Id
        {
            get
            {
                return this._Id;
            }
            set
            {
                this.OnIdChanging(value);
                if (object.Equals(this.Id, value))
                {
                    return;
                }
                this._Id = value;
                this.OnIdChanged();
                this.OnPropertyChanged("Id");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private int _Id;
        partial void OnIdChanging(int value);
        partial void OnIdChanged();
        /// <summary>
        /// There are no comments for Property InvoiceDate in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public global::System.DateTime InvoiceDate
        {
            get
            {
                return this._InvoiceDate;
            }
            set
            {
                this.OnInvoiceDateChanging(value);
                if (object.Equals(this.InvoiceDate, value))
                {
                    return;
                }
                this._InvoiceDate = value;
                this.OnInvoiceDateChanged();
                this.OnPropertyChanged("InvoiceDate");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private global::System.DateTime _InvoiceDate;
        partial void OnInvoiceDateChanging(global::System.DateTime value);
        partial void OnInvoiceDateChanged();
        /// <summary>
        /// There are no comments for Property InvoiceID in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public string InvoiceID
        {
            get
            {
                return this._InvoiceID;
            }
            set
            {
                this.OnInvoiceIDChanging(value);
                if (object.Equals(this.InvoiceID, value))
                {
                    return;
                }
                this._InvoiceID = value;
                this.OnInvoiceIDChanged();
                this.OnPropertyChanged("InvoiceID");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private string _InvoiceID;
        partial void OnInvoiceIDChanging(string value);
        partial void OnInvoiceIDChanged();
        /// <summary>
        /// There are no comments for Property IsActive in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public byte[] IsActive
        {
            get
            {
                if ((this._IsActive != null))
                {
                    return ((byte[])(this._IsActive.Clone()));
                }
                else
                {
                    return null;
                }
            }
            set
            {
                this.OnIsActiveChanging(value);
                if (object.Equals(this.IsActive, value))
                {
                    return;
                }
                this._IsActive = value;
                this.OnIsActiveChanged();
                this.OnPropertyChanged("IsActive");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private byte[] _IsActive;
        partial void OnIsActiveChanging(byte[] value);
        partial void OnIsActiveChanged();
        /// <summary>
        /// There are no comments for Property Customer_Invoice in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public int Customer_Invoice
        {
            get
            {
                return this._Customer_Invoice;
            }
            set
            {
                this.OnCustomer_InvoiceChanging(value);
                if (object.Equals(this.Customer_Invoice, value))
                {
                    return;
                }
                this._Customer_Invoice = value;
                this.OnCustomer_InvoiceChanged();
                this.OnPropertyChanged("Customer_Invoice");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private int _Customer_Invoice;
        partial void OnCustomer_InvoiceChanging(int value);
        partial void OnCustomer_InvoiceChanged();
        /// <summary>
        /// There are no comments for Property CreatedBy in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public string CreatedBy
        {
            get
            {
                return this._CreatedBy;
            }
            set
            {
                this.OnCreatedByChanging(value);
                if (object.Equals(this.CreatedBy, value))
                {
                    return;
                }
                this._CreatedBy = value;
                this.OnCreatedByChanged();
                this.OnPropertyChanged("CreatedBy");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private string _CreatedBy;
        partial void OnCreatedByChanging(string value);
        partial void OnCreatedByChanged();
        /// <summary>
        /// There are no comments for Property Created in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public global::System.Nullable<global::System.DateTimeOffset> Created
        {
            get
            {
                return this._Created;
            }
            set
            {
                this.OnCreatedChanging(value);
                if (object.Equals(this.Created, value))
                {
                    return;
                }
                this._Created = value;
                this.OnCreatedChanged();
                this.OnPropertyChanged("Created");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private global::System.Nullable<global::System.DateTimeOffset> _Created;
        partial void OnCreatedChanging(global::System.Nullable<global::System.DateTimeOffset> value);
        partial void OnCreatedChanged();
        /// <summary>
        /// There are no comments for Property ModifiedBy in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public string ModifiedBy
        {
            get
            {
                return this._ModifiedBy;
            }
            set
            {
                this.OnModifiedByChanging(value);
                if (object.Equals(this.ModifiedBy, value))
                {
                    return;
                }
                this._ModifiedBy = value;
                this.OnModifiedByChanged();
                this.OnPropertyChanged("ModifiedBy");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private string _ModifiedBy;
        partial void OnModifiedByChanging(string value);
        partial void OnModifiedByChanged();
        /// <summary>
        /// There are no comments for Property Modified in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public global::System.Nullable<global::System.DateTimeOffset> Modified
        {
            get
            {
                return this._Modified;
            }
            set
            {
                this.OnModifiedChanging(value);
                if (object.Equals(this.Modified, value))
                {
                    return;
                }
                this._Modified = value;
                this.OnModifiedChanged();
                this.OnPropertyChanged("Modified");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private global::System.Nullable<global::System.DateTimeOffset> _Modified;
        partial void OnModifiedChanging(global::System.Nullable<global::System.DateTimeOffset> value);
        partial void OnModifiedChanged();
        /// <summary>
        /// There are no comments for Property RowVersion in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public byte[] RowVersion
        {
            get
            {
                if ((this._RowVersion != null))
                {
                    return ((byte[])(this._RowVersion.Clone()));
                }
                else
                {
                    return null;
                }
            }
            set
            {
                this.OnRowVersionChanging(value);
                if (object.Equals(this.RowVersion, value))
                {
                    return;
                }
                this._RowVersion = value;
                this.OnRowVersionChanged();
                this.OnPropertyChanged("RowVersion");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private byte[] _RowVersion;
        partial void OnRowVersionChanging(byte[] value);
        partial void OnRowVersionChanged();
        /// <summary>
        /// There are no comments for InvoiceDetails in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public global::System.Data.Services.Client.DataServiceCollection<InvoiceDetail> InvoiceDetails
        {
            get
            {
                this.@__InvoiceDetails.EnsureValueInitialized();
                return this._InvoiceDetails;
            }
            set
            {
                this._InvoiceDetails = value;
                this.OnPropertyChanged("InvoiceDetails");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private global::System.Data.Services.Client.DataServiceCollection<InvoiceDetail> _InvoiceDetails = new global::System.Data.Services.Client.DataServiceCollection<InvoiceDetail>(null, global::System.Data.Services.Client.TrackingMode.None);
        /// <summary>
        /// There are no comments for Customer in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public Customer Customer
        {
            get
            {
                this.@__Customer.EnsureValueInitialized();
                return this._Customer;
            }
            set
            {
                Customer previous = this.Customer;
                if ((previous == value))
                {
                    return;
                }
                if ((previous != null))
                {
                    this._Customer = null;
                    this.@__Customer.OnValueSet();
                    previous.Invoices.Remove(this);
                }
                if ((this.___Host != null))
                {
                    if ((value != null))
                    {
                        this.Customer_Invoice = value.Id;
                    }
                    else
                    {
                        this.Customer_Invoice = default(int);
                    }
                }
                this._Customer = value;
                this.@__Customer.OnValueSet();
                if ((value != null))
                {
                    value.@__Invoices.Add(this);
                }
                this.___OnPropertyChanged("Customer");
                this.OnPropertyChanged("Customer");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private Customer _Customer;
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public event global::System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        protected virtual void OnPropertyChanged(string property)
        {
            if ((this.PropertyChanged != null))
            {
                this.PropertyChanged(this, new global::System.ComponentModel.PropertyChangedEventArgs(property));
            }
        }
    }
    /// <summary>
    /// There are no comments for LightSwitchApplication.Storage in the schema.
    /// </summary>
    /// <KeyProperties>
    /// Id
    /// </KeyProperties>
    [global::System.Data.Services.Common.EntitySetAttribute("Storages")]
    [global::System.Data.Services.Common.DataServiceKeyAttribute("Id")]
    public partial class Storage : global::Microsoft.LightSwitch.ClientGenerated.Implementation.EntityBase, global::System.ComponentModel.INotifyPropertyChanged
    {
        /// <summary>
        /// Create a new Storage object.
        /// </summary>
        /// <param name="ID">Initial value of Id.</param>
        /// <param name="storageNumber">Initial value of StorageNumber.</param>
        /// <param name="price">Initial value of Price.</param>
        /// <param name="customer_Storage">Initial value of Customer_Storage.</param>
        /// <param name="rowVersion">Initial value of RowVersion.</param>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public static Storage CreateStorage(int ID, string storageNumber, decimal price, int customer_Storage, byte[] rowVersion)
        {
            Storage storage = new Storage();
            storage.Id = ID;
            storage.StorageNumber = storageNumber;
            storage.Price = price;
            storage.Customer_Storage = customer_Storage;
            storage.RowVersion = rowVersion;
            return storage;
        }
        /// <summary>
        /// There are no comments for Property Id in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public int Id
        {
            get
            {
                return this._Id;
            }
            set
            {
                this.OnIdChanging(value);
                if (object.Equals(this.Id, value))
                {
                    return;
                }
                this._Id = value;
                this.OnIdChanged();
                this.OnPropertyChanged("Id");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private int _Id;
        partial void OnIdChanging(int value);
        partial void OnIdChanged();
        /// <summary>
        /// There are no comments for Property StorageNumber in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public string StorageNumber
        {
            get
            {
                return this._StorageNumber;
            }
            set
            {
                this.OnStorageNumberChanging(value);
                if (object.Equals(this.StorageNumber, value))
                {
                    return;
                }
                this._StorageNumber = value;
                this.OnStorageNumberChanged();
                this.OnPropertyChanged("StorageNumber");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private string _StorageNumber;
        partial void OnStorageNumberChanging(string value);
        partial void OnStorageNumberChanged();
        /// <summary>
        /// There are no comments for Property Price in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public decimal Price
        {
            get
            {
                return this._Price;
            }
            set
            {
                this.OnPriceChanging(value);
                if (object.Equals(this.Price, value))
                {
                    return;
                }
                this._Price = value;
                this.OnPriceChanged();
                this.OnPropertyChanged("Price");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private decimal _Price;
        partial void OnPriceChanging(decimal value);
        partial void OnPriceChanged();
        /// <summary>
        /// There are no comments for Property Customer_Storage in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public int Customer_Storage
        {
            get
            {
                return this._Customer_Storage;
            }
            set
            {
                this.OnCustomer_StorageChanging(value);
                if (object.Equals(this.Customer_Storage, value))
                {
                    return;
                }
                this._Customer_Storage = value;
                this.OnCustomer_StorageChanged();
                this.OnPropertyChanged("Customer_Storage");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private int _Customer_Storage;
        partial void OnCustomer_StorageChanging(int value);
        partial void OnCustomer_StorageChanged();
        /// <summary>
        /// There are no comments for Property CreatedBy in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public string CreatedBy
        {
            get
            {
                return this._CreatedBy;
            }
            set
            {
                this.OnCreatedByChanging(value);
                if (object.Equals(this.CreatedBy, value))
                {
                    return;
                }
                this._CreatedBy = value;
                this.OnCreatedByChanged();
                this.OnPropertyChanged("CreatedBy");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private string _CreatedBy;
        partial void OnCreatedByChanging(string value);
        partial void OnCreatedByChanged();
        /// <summary>
        /// There are no comments for Property Created in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public global::System.Nullable<global::System.DateTimeOffset> Created
        {
            get
            {
                return this._Created;
            }
            set
            {
                this.OnCreatedChanging(value);
                if (object.Equals(this.Created, value))
                {
                    return;
                }
                this._Created = value;
                this.OnCreatedChanged();
                this.OnPropertyChanged("Created");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private global::System.Nullable<global::System.DateTimeOffset> _Created;
        partial void OnCreatedChanging(global::System.Nullable<global::System.DateTimeOffset> value);
        partial void OnCreatedChanged();
        /// <summary>
        /// There are no comments for Property ModifiedBy in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public string ModifiedBy
        {
            get
            {
                return this._ModifiedBy;
            }
            set
            {
                this.OnModifiedByChanging(value);
                if (object.Equals(this.ModifiedBy, value))
                {
                    return;
                }
                this._ModifiedBy = value;
                this.OnModifiedByChanged();
                this.OnPropertyChanged("ModifiedBy");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private string _ModifiedBy;
        partial void OnModifiedByChanging(string value);
        partial void OnModifiedByChanged();
        /// <summary>
        /// There are no comments for Property Modified in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public global::System.Nullable<global::System.DateTimeOffset> Modified
        {
            get
            {
                return this._Modified;
            }
            set
            {
                this.OnModifiedChanging(value);
                if (object.Equals(this.Modified, value))
                {
                    return;
                }
                this._Modified = value;
                this.OnModifiedChanged();
                this.OnPropertyChanged("Modified");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private global::System.Nullable<global::System.DateTimeOffset> _Modified;
        partial void OnModifiedChanging(global::System.Nullable<global::System.DateTimeOffset> value);
        partial void OnModifiedChanged();
        /// <summary>
        /// There are no comments for Property RowVersion in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public byte[] RowVersion
        {
            get
            {
                if ((this._RowVersion != null))
                {
                    return ((byte[])(this._RowVersion.Clone()));
                }
                else
                {
                    return null;
                }
            }
            set
            {
                this.OnRowVersionChanging(value);
                if (object.Equals(this.RowVersion, value))
                {
                    return;
                }
                this._RowVersion = value;
                this.OnRowVersionChanged();
                this.OnPropertyChanged("RowVersion");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private byte[] _RowVersion;
        partial void OnRowVersionChanging(byte[] value);
        partial void OnRowVersionChanged();
        /// <summary>
        /// There are no comments for Customer in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public Customer Customer
        {
            get
            {
                this.@__Customer.EnsureValueInitialized();
                return this._Customer;
            }
            set
            {
                Customer previous = this.Customer;
                if ((previous == value))
                {
                    return;
                }
                if ((previous != null))
                {
                    this._Customer = null;
                    this.@__Customer.OnValueSet();
                    previous.Storages.Remove(this);
                }
                if ((this.___Host != null))
                {
                    if ((value != null))
                    {
                        this.Customer_Storage = value.Id;
                    }
                    else
                    {
                        this.Customer_Storage = default(int);
                    }
                }
                this._Customer = value;
                this.@__Customer.OnValueSet();
                if ((value != null))
                {
                    value.@__Storages.Add(this);
                }
                this.___OnPropertyChanged("Customer");
                this.OnPropertyChanged("Customer");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private Customer _Customer;
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public event global::System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        protected virtual void OnPropertyChanged(string property)
        {
            if ((this.PropertyChanged != null))
            {
                this.PropertyChanged(this, new global::System.ComponentModel.PropertyChangedEventArgs(property));
            }
        }
    }
}
