//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LightSwitchApplication
{
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "12.1.0.0")]
    public sealed partial class MainScreen
        : global::Microsoft.LightSwitch.Framework.Client.ScreenObject<global::LightSwitchApplication.MainScreen, global::LightSwitchApplication.MainScreen.DetailsClass>
    {
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "12.1.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        private MainScreen() : base("LightSwitchApplication.Invoices.DesktopClient:MainScreen")
        {
            global::LightSwitchApplication.MainScreen.DetailsClass.Initialize(this);
        }

        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "12.1.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public static MainScreen CreateInstance()
        {
            return new global::LightSwitchApplication.MainScreen(
            );
        }

        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void MainScreen_InitializeDataWorkspace(global::System.Collections.Generic.List<global::Microsoft.LightSwitch.IDataService> saveChangesTo);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void MainScreen_Created();
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void MainScreen_Activated();
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void MainScreen_Saving(ref bool handled);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void MainScreen_Saved();
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void MainScreen_Closing(ref bool cancel);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void MainScreen_SaveError(global::System.Exception exception, ref bool handled);
     
        #region Private Properties
        
        /// <summary>
        /// Gets the Application object for this application.  The Application object provides access to active screens, methods to open screens and access to the current user.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "12.1.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        private global::LightSwitchApplication.Application Application
        {
            get
            {
                return global::LightSwitchApplication.Application.Current;
            }
        }
        
        /// <summary>
        /// Gets the containing data workspace.  The data workspace provides access to all data sources in the application.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "12.1.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        private global::LightSwitchApplication.DataWorkspace DataWorkspace
        {
            get
            {
                return (global::LightSwitchApplication.DataWorkspace)((global::Microsoft.LightSwitch.Details.Client.IScreenDetails)this.Details).DataWorkspace;
            }
        }
        
        #endregion
 
        partial void Customers_SelectionChanged();

        partial void Customers_Changed(global::System.Collections.Specialized.NotifyCollectionChangedEventArgs e);

        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void Customers_Loaded(bool succeeded);

        partial void Invoices_SelectionChanged();

        partial void Invoices_Changed(global::System.Collections.Specialized.NotifyCollectionChangedEventArgs e);

        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void Invoices_Loaded(bool succeeded);

        partial void Storages_SelectionChanged();

        partial void Storages_Changed(global::System.Collections.Specialized.NotifyCollectionChangedEventArgs e);

        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void Storages_Loaded(bool succeeded);

        /// <summary>
        /// Gets the Customers visual collection. The collection contains all records currently shown on the respective list or grid control.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "12.1.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public global::Microsoft.LightSwitch.Framework.Client.VisualCollection<global::LightSwitchApplication.Customer> Customers
        {
            get
            {
                return global::LightSwitchApplication.MainScreen.DetailsClass.GetValue(this, global::LightSwitchApplication.MainScreen.DetailsClass.PropertySetProperties.Customers);
            }
        }
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void Customers_Validate(global::Microsoft.LightSwitch.Framework.Client.ScreenValidationResultsBuilder results);
 
        /// <summary>
        /// Gets the Invoices visual collection. The collection contains all records currently shown on the respective list or grid control.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "12.1.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public global::Microsoft.LightSwitch.Framework.Client.VisualCollection<global::LightSwitchApplication.Invoice> Invoices
        {
            get
            {
                return global::LightSwitchApplication.MainScreen.DetailsClass.GetValue(this, global::LightSwitchApplication.MainScreen.DetailsClass.PropertySetProperties.Invoices);
            }
        }
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void Invoices_Validate(global::Microsoft.LightSwitch.Framework.Client.ScreenValidationResultsBuilder results);
 
        /// <summary>
        /// Gets the Storages visual collection. The collection contains all records currently shown on the respective list or grid control.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "12.1.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public global::Microsoft.LightSwitch.Framework.Client.VisualCollection<global::LightSwitchApplication.Storage> Storages
        {
            get
            {
                return global::LightSwitchApplication.MainScreen.DetailsClass.GetValue(this, global::LightSwitchApplication.MainScreen.DetailsClass.PropertySetProperties.Storages);
            }
        }
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void Storages_Validate(global::Microsoft.LightSwitch.Framework.Client.ScreenValidationResultsBuilder results);
 
        /// <summary>
        /// Calls the Invoicebtn screen method.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "12.1.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public void Invoicebtn()
        {
            this.Details.Methods.Invoicebtn.CreateInvocation().Execute();
        }
        partial void Invoicebtn_CanExecute(ref bool result);
        partial void Invoicebtn_Execute();

        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "12.1.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public sealed class DetailsClass
            : global::Microsoft.LightSwitch.Details.Framework.Client.ScreenDetails<global::LightSwitchApplication.MainScreen, global::LightSwitchApplication.MainScreen.DetailsClass, global::LightSwitchApplication.MainScreen.DetailsClass.PropertySet, global::LightSwitchApplication.MainScreen.DetailsClass.CommandSet, global::LightSwitchApplication.MainScreen.DetailsClass.MethodSet>
        {

            static DetailsClass()
            {
                var initializePropertyEntry = global::LightSwitchApplication.MainScreen.DetailsClass.PropertySetProperties.Customers;
                var initializeCommandEntry = global::LightSwitchApplication.MainScreen.DetailsClass.CommandSetProperties.Invoicebtn;
                var initializeMethodEntry = global::LightSwitchApplication.MainScreen.DetailsClass.MethodSetProperties.Invoicebtn;
            }

            [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
            private static global::Microsoft.LightSwitch.Details.Framework.Client.ScreenDetails<global::LightSwitchApplication.MainScreen, global::LightSwitchApplication.MainScreen.DetailsClass>.Entry
                __MainScreenEntry = new global::Microsoft.LightSwitch.Details.Framework.Client.ScreenDetails<global::LightSwitchApplication.MainScreen, global::LightSwitchApplication.MainScreen.DetailsClass>.Entry(
                    global::LightSwitchApplication.MainScreen.DetailsClass.__MainScreen_InvokeInitializeDataWorkspace,
                    global::LightSwitchApplication.MainScreen.DetailsClass.__MainScreen_InvokeSavingEvent,
                    global::LightSwitchApplication.MainScreen.DetailsClass.__MainScreen_InvokeSavedEvent,
                    global::LightSwitchApplication.MainScreen.DetailsClass.__MainScreen_InvokeClosingEvent,
                    global::LightSwitchApplication.MainScreen.DetailsClass.__MainScreen_InvokeCreated,
                    global::LightSwitchApplication.MainScreen.DetailsClass.__MainScreen_InvokeActivated,
                    global::LightSwitchApplication.MainScreen.DetailsClass.__MainScreen_InvokeSaveErrorEvent);
            private static void __MainScreen_InvokeInitializeDataWorkspace(global::LightSwitchApplication.MainScreen s, global::System.Collections.Generic.List<global::Microsoft.LightSwitch.IDataService> saveChangesTo)
            {
                s.MainScreen_InitializeDataWorkspace(saveChangesTo);
            }
            private static bool __MainScreen_InvokeSavingEvent(global::LightSwitchApplication.MainScreen s)
            {
                bool handled = false;
                s.MainScreen_Saving(ref handled);
                return handled;
            }
            private static void __MainScreen_InvokeSavedEvent(global::LightSwitchApplication.MainScreen s)
            {
                s.MainScreen_Saved();
            }
            private static bool __MainScreen_InvokeClosingEvent(global::LightSwitchApplication.MainScreen s)
            {
                bool cancel = false;
                s.MainScreen_Closing(ref cancel);
                return cancel;
            }
            private static void __MainScreen_InvokeCreated(global::LightSwitchApplication.MainScreen s)
            {
                s.MainScreen_Created();
            }
            private static void __MainScreen_InvokeActivated(global::LightSwitchApplication.MainScreen s)
            {
                s.MainScreen_Activated();
            }
            private static bool __MainScreen_InvokeSaveErrorEvent(global::LightSwitchApplication.MainScreen s, global::System.Exception ex)
            {
                bool handled = false;
                s.MainScreen_SaveError(ex, ref handled);
                return handled;
            }

            public DetailsClass() : base()
            {
            }

            public new global::LightSwitchApplication.MainScreen.DetailsClass.PropertySet Properties
            {
                get
                {
                    return base.Properties;
                }
            }

            public new global::LightSwitchApplication.MainScreen.DetailsClass.CommandSet Commands
            {
                get
                {
                    return base.Commands;
                }
            }

            public new global::LightSwitchApplication.MainScreen.DetailsClass.MethodSet Methods
            {
                get
                {
                    return base.Methods;
                }
            }

            private global::Microsoft.LightSwitch.IDataServiceQueryable CustomersQuery()
            {
                return this.Screen.DataWorkspace.ApplicationData.Customers;
            }

            private global::Microsoft.LightSwitch.IDataServiceQueryable InvoicesQuery()
            {
                if (this.Screen.Customers.SelectedItem == null)
                {
                    return null;
                }

                global::Microsoft.LightSwitch.IDataServiceQueryable<global::LightSwitchApplication.Invoice> loader =
                    (global::Microsoft.LightSwitch.IDataServiceQueryable<global::LightSwitchApplication.Invoice>)((global::Microsoft.LightSwitch.Details.ILoadableProperty)this.Screen.Customers.SelectedItem.Details.Properties.Invoices).Loader;
                if (loader == null)
                {
                    return null;
                }

                return global::Microsoft.LightSwitch.DataServiceQueryable.Include(
                    loader,
                    "Customer");
            }

            private global::Microsoft.LightSwitch.IDataServiceQueryable StoragesQuery()
            {
                if (this.Screen.Customers.SelectedItem == null)
                {
                    return null;
                }

                global::Microsoft.LightSwitch.IDataServiceQueryable<global::LightSwitchApplication.Storage> loader =
                    (global::Microsoft.LightSwitch.IDataServiceQueryable<global::LightSwitchApplication.Storage>)((global::Microsoft.LightSwitch.Details.ILoadableProperty)this.Screen.Customers.SelectedItem.Details.Properties.Storages).Loader;
                if (loader == null)
                {
                    return null;
                }

                return loader;
            }

            [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
            private global::Microsoft.LightSwitch.Details.Framework.Client.ScreenCollectionProperty<global::LightSwitchApplication.MainScreen, global::LightSwitchApplication.MainScreen.DetailsClass, global::LightSwitchApplication.Customer>.Data _Customers;

            [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
            private global::Microsoft.LightSwitch.Details.Framework.Client.ScreenCollectionProperty<global::LightSwitchApplication.MainScreen, global::LightSwitchApplication.MainScreen.DetailsClass, global::LightSwitchApplication.Invoice>.Data _Invoices;

            [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
            private global::Microsoft.LightSwitch.Details.Framework.Client.ScreenCollectionProperty<global::LightSwitchApplication.MainScreen, global::LightSwitchApplication.MainScreen.DetailsClass, global::LightSwitchApplication.Storage>.Data _Storages;

            [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
            private global::Microsoft.LightSwitch.Details.Framework.Client.ScreenCommand<global::LightSwitchApplication.MainScreen, global::LightSwitchApplication.MainScreen.DetailsClass>.Data _InvoicebtnCommand;

            [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
            private global::Microsoft.LightSwitch.Details.Framework.Client.ScreenMethod<global::LightSwitchApplication.MainScreen, global::LightSwitchApplication.MainScreen.DetailsClass>.Data _InvoicebtnMethod;

            [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "12.1.0.0")]
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public sealed class PropertySet
                : global::Microsoft.LightSwitch.Details.Framework.Client.ScreenPropertySet<global::LightSwitchApplication.MainScreen, global::LightSwitchApplication.MainScreen.DetailsClass>
            {

                public global::Microsoft.LightSwitch.Details.Framework.Client.ScreenCollectionProperty<global::LightSwitchApplication.MainScreen, global::LightSwitchApplication.MainScreen.DetailsClass, global::LightSwitchApplication.Customer> Customers
                {
                    get
                    {
                        return (global::Microsoft.LightSwitch.Details.Framework.Client.ScreenCollectionProperty<global::LightSwitchApplication.MainScreen, global::LightSwitchApplication.MainScreen.DetailsClass, global::LightSwitchApplication.Customer>)base.GetItem(global::LightSwitchApplication.MainScreen.DetailsClass.PropertySetProperties.Customers);
                    }
                }

                public global::Microsoft.LightSwitch.Details.Framework.Client.ScreenCollectionProperty<global::LightSwitchApplication.MainScreen, global::LightSwitchApplication.MainScreen.DetailsClass, global::LightSwitchApplication.Invoice> Invoices
                {
                    get
                    {
                        return (global::Microsoft.LightSwitch.Details.Framework.Client.ScreenCollectionProperty<global::LightSwitchApplication.MainScreen, global::LightSwitchApplication.MainScreen.DetailsClass, global::LightSwitchApplication.Invoice>)base.GetItem(global::LightSwitchApplication.MainScreen.DetailsClass.PropertySetProperties.Invoices);
                    }
                }

                public global::Microsoft.LightSwitch.Details.Framework.Client.ScreenCollectionProperty<global::LightSwitchApplication.MainScreen, global::LightSwitchApplication.MainScreen.DetailsClass, global::LightSwitchApplication.Storage> Storages
                {
                    get
                    {
                        return (global::Microsoft.LightSwitch.Details.Framework.Client.ScreenCollectionProperty<global::LightSwitchApplication.MainScreen, global::LightSwitchApplication.MainScreen.DetailsClass, global::LightSwitchApplication.Storage>)base.GetItem(global::LightSwitchApplication.MainScreen.DetailsClass.PropertySetProperties.Storages);
                    }
                }

            }

            [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "12.1.0.0")]
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public sealed class CommandSet
                : global::Microsoft.LightSwitch.Details.Framework.Client.ScreenCommandSet<global::LightSwitchApplication.MainScreen, global::LightSwitchApplication.MainScreen.DetailsClass>
            {

                public global::Microsoft.LightSwitch.Details.Framework.Client.ScreenCommand<global::LightSwitchApplication.MainScreen, global::LightSwitchApplication.MainScreen.DetailsClass> Invoicebtn
                {
                    get
                    {
                        return (global::Microsoft.LightSwitch.Details.Framework.Client.ScreenCommand<global::LightSwitchApplication.MainScreen, global::LightSwitchApplication.MainScreen.DetailsClass>)base.GetItem(global::LightSwitchApplication.MainScreen.DetailsClass.CommandSetProperties.Invoicebtn);
                    }
                }

            }

            [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "12.1.0.0")]
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public sealed class MethodSet
                : global::Microsoft.LightSwitch.Details.Framework.Client.ScreenMethodSet<global::LightSwitchApplication.MainScreen, global::LightSwitchApplication.MainScreen.DetailsClass>
            {

                public global::Microsoft.LightSwitch.Details.Framework.Client.ScreenMethod<global::LightSwitchApplication.MainScreen, global::LightSwitchApplication.MainScreen.DetailsClass> Invoicebtn
                {
                    get
                    {
                        return (global::Microsoft.LightSwitch.Details.Framework.Client.ScreenMethod<global::LightSwitchApplication.MainScreen, global::LightSwitchApplication.MainScreen.DetailsClass>)base.GetItem(global::LightSwitchApplication.MainScreen.DetailsClass.MethodSetProperties.Invoicebtn);
                    }
                }

            }

            [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "12.1.0.0")]
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            internal sealed class PropertySetProperties
            {

                public static readonly global::Microsoft.LightSwitch.Details.Framework.Client.ScreenCollectionProperty<global::LightSwitchApplication.MainScreen, global::LightSwitchApplication.MainScreen.DetailsClass, global::LightSwitchApplication.Customer>.Entry
                    Customers = new global::Microsoft.LightSwitch.Details.Framework.Client.ScreenCollectionProperty<global::LightSwitchApplication.MainScreen, global::LightSwitchApplication.MainScreen.DetailsClass, global::LightSwitchApplication.Customer>.Entry(
                        "Customers",
                        global::LightSwitchApplication.MainScreen.DetailsClass.PropertySetProperties._Customers_Stub,
                        global::LightSwitchApplication.MainScreen.DetailsClass.PropertySetProperties._Customers_Validate,
                        global::LightSwitchApplication.MainScreen.DetailsClass.PropertySetProperties._Customers_CreateQuery,
                        global::LightSwitchApplication.MainScreen.DetailsClass.PropertySetProperties._Customers_SelectionChanged,
                        global::LightSwitchApplication.MainScreen.DetailsClass.PropertySetProperties._Customers_OnCollectionChanged,
                        global::LightSwitchApplication.MainScreen.DetailsClass.PropertySetProperties._Customers_OnLoaded);
                private static void _Customers_Stub(global::Microsoft.LightSwitch.Details.Framework.Base.DetailsCallback<global::LightSwitchApplication.MainScreen.DetailsClass, global::Microsoft.LightSwitch.Details.Framework.Client.ScreenCollectionProperty<global::LightSwitchApplication.MainScreen, global::LightSwitchApplication.MainScreen.DetailsClass, global::LightSwitchApplication.Customer>.Data> c, global::LightSwitchApplication.MainScreen.DetailsClass d, object sf)
                {
                    c(d, ref d._Customers, sf);
                }
                private static void _Customers_Validate(global::LightSwitchApplication.MainScreen s, global::Microsoft.LightSwitch.Framework.Client.ScreenValidationResultsBuilder r)
                {
                    s.Customers_Validate(r);
                }
                private static global::Microsoft.LightSwitch.IDataServiceQueryable _Customers_CreateQuery(global::LightSwitchApplication.MainScreen.DetailsClass d, object[] args)
                {
                    return d.CustomersQuery();
                }
                private static void _Customers_SelectionChanged(global::LightSwitchApplication.MainScreen s)
                {
                    s.Customers_SelectionChanged();
                }
                private static void _Customers_OnCollectionChanged(global::LightSwitchApplication.MainScreen s, global::System.Collections.Specialized.NotifyCollectionChangedEventArgs e)
                {
                    s.Customers_Changed(e);
                }
                private static void _Customers_OnLoaded(global::LightSwitchApplication.MainScreen s, bool succeeded)
                {
                    s.Customers_Loaded(succeeded);
                }

                public static readonly global::Microsoft.LightSwitch.Details.Framework.Client.ScreenCollectionProperty<global::LightSwitchApplication.MainScreen, global::LightSwitchApplication.MainScreen.DetailsClass, global::LightSwitchApplication.Invoice>.Entry
                    Invoices = new global::Microsoft.LightSwitch.Details.Framework.Client.ScreenCollectionProperty<global::LightSwitchApplication.MainScreen, global::LightSwitchApplication.MainScreen.DetailsClass, global::LightSwitchApplication.Invoice>.Entry(
                        "Invoices",
                        global::LightSwitchApplication.MainScreen.DetailsClass.PropertySetProperties._Invoices_Stub,
                        global::LightSwitchApplication.MainScreen.DetailsClass.PropertySetProperties._Invoices_Validate,
                        global::LightSwitchApplication.MainScreen.DetailsClass.PropertySetProperties._Invoices_CreateQuery,
                        global::LightSwitchApplication.MainScreen.DetailsClass.PropertySetProperties._Invoices_SelectionChanged,
                        global::LightSwitchApplication.MainScreen.DetailsClass.PropertySetProperties._Invoices_OnCollectionChanged,
                        global::LightSwitchApplication.MainScreen.DetailsClass.PropertySetProperties._Invoices_OnLoaded);
                private static void _Invoices_Stub(global::Microsoft.LightSwitch.Details.Framework.Base.DetailsCallback<global::LightSwitchApplication.MainScreen.DetailsClass, global::Microsoft.LightSwitch.Details.Framework.Client.ScreenCollectionProperty<global::LightSwitchApplication.MainScreen, global::LightSwitchApplication.MainScreen.DetailsClass, global::LightSwitchApplication.Invoice>.Data> c, global::LightSwitchApplication.MainScreen.DetailsClass d, object sf)
                {
                    c(d, ref d._Invoices, sf);
                }
                private static void _Invoices_Validate(global::LightSwitchApplication.MainScreen s, global::Microsoft.LightSwitch.Framework.Client.ScreenValidationResultsBuilder r)
                {
                    s.Invoices_Validate(r);
                }
                private static global::Microsoft.LightSwitch.IDataServiceQueryable _Invoices_CreateQuery(global::LightSwitchApplication.MainScreen.DetailsClass d, object[] args)
                {
                    return d.InvoicesQuery();
                }
                private static void _Invoices_SelectionChanged(global::LightSwitchApplication.MainScreen s)
                {
                    s.Invoices_SelectionChanged();
                }
                private static void _Invoices_OnCollectionChanged(global::LightSwitchApplication.MainScreen s, global::System.Collections.Specialized.NotifyCollectionChangedEventArgs e)
                {
                    s.Invoices_Changed(e);
                }
                private static void _Invoices_OnLoaded(global::LightSwitchApplication.MainScreen s, bool succeeded)
                {
                    s.Invoices_Loaded(succeeded);
                }

                public static readonly global::Microsoft.LightSwitch.Details.Framework.Client.ScreenCollectionProperty<global::LightSwitchApplication.MainScreen, global::LightSwitchApplication.MainScreen.DetailsClass, global::LightSwitchApplication.Storage>.Entry
                    Storages = new global::Microsoft.LightSwitch.Details.Framework.Client.ScreenCollectionProperty<global::LightSwitchApplication.MainScreen, global::LightSwitchApplication.MainScreen.DetailsClass, global::LightSwitchApplication.Storage>.Entry(
                        "Storages",
                        global::LightSwitchApplication.MainScreen.DetailsClass.PropertySetProperties._Storages_Stub,
                        global::LightSwitchApplication.MainScreen.DetailsClass.PropertySetProperties._Storages_Validate,
                        global::LightSwitchApplication.MainScreen.DetailsClass.PropertySetProperties._Storages_CreateQuery,
                        global::LightSwitchApplication.MainScreen.DetailsClass.PropertySetProperties._Storages_SelectionChanged,
                        global::LightSwitchApplication.MainScreen.DetailsClass.PropertySetProperties._Storages_OnCollectionChanged,
                        global::LightSwitchApplication.MainScreen.DetailsClass.PropertySetProperties._Storages_OnLoaded);
                private static void _Storages_Stub(global::Microsoft.LightSwitch.Details.Framework.Base.DetailsCallback<global::LightSwitchApplication.MainScreen.DetailsClass, global::Microsoft.LightSwitch.Details.Framework.Client.ScreenCollectionProperty<global::LightSwitchApplication.MainScreen, global::LightSwitchApplication.MainScreen.DetailsClass, global::LightSwitchApplication.Storage>.Data> c, global::LightSwitchApplication.MainScreen.DetailsClass d, object sf)
                {
                    c(d, ref d._Storages, sf);
                }
                private static void _Storages_Validate(global::LightSwitchApplication.MainScreen s, global::Microsoft.LightSwitch.Framework.Client.ScreenValidationResultsBuilder r)
                {
                    s.Storages_Validate(r);
                }
                private static global::Microsoft.LightSwitch.IDataServiceQueryable _Storages_CreateQuery(global::LightSwitchApplication.MainScreen.DetailsClass d, object[] args)
                {
                    return d.StoragesQuery();
                }
                private static void _Storages_SelectionChanged(global::LightSwitchApplication.MainScreen s)
                {
                    s.Storages_SelectionChanged();
                }
                private static void _Storages_OnCollectionChanged(global::LightSwitchApplication.MainScreen s, global::System.Collections.Specialized.NotifyCollectionChangedEventArgs e)
                {
                    s.Storages_Changed(e);
                }
                private static void _Storages_OnLoaded(global::LightSwitchApplication.MainScreen s, bool succeeded)
                {
                    s.Storages_Loaded(succeeded);
                }

            }

            [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "12.1.0.0")]
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            internal sealed class CommandSetProperties
            {

                public static readonly global::Microsoft.LightSwitch.Details.Framework.Client.ScreenCommand<global::LightSwitchApplication.MainScreen, global::LightSwitchApplication.MainScreen.DetailsClass>.Entry
                    Invoicebtn = new global::Microsoft.LightSwitch.Details.Framework.Client.ScreenCommand<global::LightSwitchApplication.MainScreen, global::LightSwitchApplication.MainScreen.DetailsClass>.Entry(
                        "Invoicebtn",
                        global::LightSwitchApplication.MainScreen.DetailsClass.CommandSetProperties._Invoicebtn_Stub,
                        global::LightSwitchApplication.MainScreen.DetailsClass.CommandSetProperties._Invoicebtn_CreateExecutableObject);
                private static void _Invoicebtn_Stub(global::Microsoft.LightSwitch.Details.Framework.Base.DetailsCallback<global::LightSwitchApplication.MainScreen.DetailsClass, global::Microsoft.LightSwitch.Details.Framework.Client.ScreenCommand<global::LightSwitchApplication.MainScreen, global::LightSwitchApplication.MainScreen.DetailsClass>.Data> c, global::LightSwitchApplication.MainScreen.DetailsClass d, object sf)
                {
                    c(d, ref d._InvoicebtnCommand, sf);
                }
                private static global::Microsoft.LightSwitch.IExecutable _Invoicebtn_CreateExecutableObject(global::LightSwitchApplication.MainScreen.DetailsClass d)
                {
                    return ((global::LightSwitchApplication.MainScreen.DetailsClass)d).Methods.Invoicebtn.CreateInvocation();
                }

            }

            [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "12.1.0.0")]
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            internal sealed class MethodSetProperties
            {

                public static readonly global::Microsoft.LightSwitch.Details.Framework.Client.ScreenMethod<global::LightSwitchApplication.MainScreen, global::LightSwitchApplication.MainScreen.DetailsClass>.Entry
                    Invoicebtn = new global::Microsoft.LightSwitch.Details.Framework.Client.ScreenMethod<global::LightSwitchApplication.MainScreen, global::LightSwitchApplication.MainScreen.DetailsClass>.Entry(
                        "Invoicebtn",
                        global::LightSwitchApplication.MainScreen.DetailsClass.MethodSetProperties._Invoicebtn_Stub,
                        global::LightSwitchApplication.MainScreen.DetailsClass.MethodSetProperties._Invoicebtn_CanInvoke,
                        global::LightSwitchApplication.MainScreen.DetailsClass.MethodSetProperties._Invoicebtn_InvokeMethod);
                private static void _Invoicebtn_Stub(global::Microsoft.LightSwitch.Details.Framework.Base.DetailsCallback<global::LightSwitchApplication.MainScreen.DetailsClass, global::Microsoft.LightSwitch.Details.Framework.Client.ScreenMethod<global::LightSwitchApplication.MainScreen, global::LightSwitchApplication.MainScreen.DetailsClass>.Data> c, global::LightSwitchApplication.MainScreen.DetailsClass d, object sf)
                {
                    c(d, ref d._InvoicebtnMethod, sf);
                }
                private static global::System.Exception _Invoicebtn_CanInvoke(global::LightSwitchApplication.MainScreen.DetailsClass d, global::System.Collections.ObjectModel.ReadOnlyCollection<object> args, global::System.Exception ex)
                {
                    bool result = true;
                    d.Screen.Invoicebtn_CanExecute(ref result);
                    return result ? null : ex;
                }
                private static void _Invoicebtn_InvokeMethod(global::LightSwitchApplication.MainScreen.DetailsClass d, global::System.Collections.ObjectModel.ReadOnlyCollection<object> args)
                {
                    d.Screen.Invoicebtn_Execute();
                }

            }
        }
    }
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "12.1.0.0")]
    public sealed partial class NewInvoiceScreen
        : global::Microsoft.LightSwitch.Framework.Client.ScreenObject<global::LightSwitchApplication.NewInvoiceScreen, global::LightSwitchApplication.NewInvoiceScreen.DetailsClass>
    {
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "12.1.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        private NewInvoiceScreen() : base("LightSwitchApplication.Invoices.DesktopClient:NewInvoiceScreen")
        {
            global::LightSwitchApplication.NewInvoiceScreen.DetailsClass.Initialize(this);
        }

        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "12.1.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public static NewInvoiceScreen CreateInstance()
        {
            return new global::LightSwitchApplication.NewInvoiceScreen(
            );
        }

        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void NewInvoiceScreen_InitializeDataWorkspace(global::System.Collections.Generic.List<global::Microsoft.LightSwitch.IDataService> saveChangesTo);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void NewInvoiceScreen_Created();
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void NewInvoiceScreen_Activated();
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void NewInvoiceScreen_Saving(ref bool handled);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void NewInvoiceScreen_Saved();
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void NewInvoiceScreen_Closing(ref bool cancel);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void NewInvoiceScreen_SaveError(global::System.Exception exception, ref bool handled);
     
        #region Private Properties
        
        /// <summary>
        /// Gets the Application object for this application.  The Application object provides access to active screens, methods to open screens and access to the current user.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "12.1.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        private global::LightSwitchApplication.Application Application
        {
            get
            {
                return global::LightSwitchApplication.Application.Current;
            }
        }
        
        /// <summary>
        /// Gets the containing data workspace.  The data workspace provides access to all data sources in the application.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "12.1.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        private global::LightSwitchApplication.DataWorkspace DataWorkspace
        {
            get
            {
                return (global::LightSwitchApplication.DataWorkspace)((global::Microsoft.LightSwitch.Details.Client.IScreenDetails)this.Details).DataWorkspace;
            }
        }
        
        #endregion
 
        partial void InvoiceProperty_Changed();

        partial void InvoiceDetails_SelectionChanged();

        partial void InvoiceDetails_Changed(global::System.Collections.Specialized.NotifyCollectionChangedEventArgs e);

        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void InvoiceDetails_Loaded(bool succeeded);

        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "12.1.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public global::LightSwitchApplication.Invoice InvoiceProperty
        {
            get 
            {
                return global::LightSwitchApplication.NewInvoiceScreen.DetailsClass.GetValue(this, global::LightSwitchApplication.NewInvoiceScreen.DetailsClass.PropertySetProperties.InvoiceProperty);
            }
            set
            {
                global::LightSwitchApplication.NewInvoiceScreen.DetailsClass.SetValue(this, global::LightSwitchApplication.NewInvoiceScreen.DetailsClass.PropertySetProperties.InvoiceProperty, value);
            }
        }
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void InvoiceProperty_Validate(global::Microsoft.LightSwitch.Framework.Client.ScreenValidationResultsBuilder results);
 
        /// <summary>
        /// Gets the InvoiceDetails visual collection. The collection contains all records currently shown on the respective list or grid control.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "12.1.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public global::Microsoft.LightSwitch.Framework.Client.VisualCollection<global::LightSwitchApplication.InvoiceDetail> InvoiceDetails
        {
            get
            {
                return global::LightSwitchApplication.NewInvoiceScreen.DetailsClass.GetValue(this, global::LightSwitchApplication.NewInvoiceScreen.DetailsClass.PropertySetProperties.InvoiceDetails);
            }
        }
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void InvoiceDetails_Validate(global::Microsoft.LightSwitch.Framework.Client.ScreenValidationResultsBuilder results);
 
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "12.1.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public sealed class DetailsClass
            : global::Microsoft.LightSwitch.Details.Framework.Client.ScreenDetails<global::LightSwitchApplication.NewInvoiceScreen, global::LightSwitchApplication.NewInvoiceScreen.DetailsClass, global::LightSwitchApplication.NewInvoiceScreen.DetailsClass.PropertySet, global::LightSwitchApplication.NewInvoiceScreen.DetailsClass.CommandSet, global::LightSwitchApplication.NewInvoiceScreen.DetailsClass.MethodSet>
        {

            static DetailsClass()
            {
                var initializePropertyEntry = global::LightSwitchApplication.NewInvoiceScreen.DetailsClass.PropertySetProperties.InvoiceProperty;
            }

            [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
            private static global::Microsoft.LightSwitch.Details.Framework.Client.ScreenDetails<global::LightSwitchApplication.NewInvoiceScreen, global::LightSwitchApplication.NewInvoiceScreen.DetailsClass>.Entry
                __NewInvoiceScreenEntry = new global::Microsoft.LightSwitch.Details.Framework.Client.ScreenDetails<global::LightSwitchApplication.NewInvoiceScreen, global::LightSwitchApplication.NewInvoiceScreen.DetailsClass>.Entry(
                    global::LightSwitchApplication.NewInvoiceScreen.DetailsClass.__NewInvoiceScreen_InvokeInitializeDataWorkspace,
                    global::LightSwitchApplication.NewInvoiceScreen.DetailsClass.__NewInvoiceScreen_InvokeSavingEvent,
                    global::LightSwitchApplication.NewInvoiceScreen.DetailsClass.__NewInvoiceScreen_InvokeSavedEvent,
                    global::LightSwitchApplication.NewInvoiceScreen.DetailsClass.__NewInvoiceScreen_InvokeClosingEvent,
                    global::LightSwitchApplication.NewInvoiceScreen.DetailsClass.__NewInvoiceScreen_InvokeCreated,
                    global::LightSwitchApplication.NewInvoiceScreen.DetailsClass.__NewInvoiceScreen_InvokeActivated,
                    global::LightSwitchApplication.NewInvoiceScreen.DetailsClass.__NewInvoiceScreen_InvokeSaveErrorEvent);
            private static void __NewInvoiceScreen_InvokeInitializeDataWorkspace(global::LightSwitchApplication.NewInvoiceScreen s, global::System.Collections.Generic.List<global::Microsoft.LightSwitch.IDataService> saveChangesTo)
            {
                s.NewInvoiceScreen_InitializeDataWorkspace(saveChangesTo);
            }
            private static bool __NewInvoiceScreen_InvokeSavingEvent(global::LightSwitchApplication.NewInvoiceScreen s)
            {
                bool handled = false;
                s.NewInvoiceScreen_Saving(ref handled);
                return handled;
            }
            private static void __NewInvoiceScreen_InvokeSavedEvent(global::LightSwitchApplication.NewInvoiceScreen s)
            {
                s.NewInvoiceScreen_Saved();
            }
            private static bool __NewInvoiceScreen_InvokeClosingEvent(global::LightSwitchApplication.NewInvoiceScreen s)
            {
                bool cancel = false;
                s.NewInvoiceScreen_Closing(ref cancel);
                return cancel;
            }
            private static void __NewInvoiceScreen_InvokeCreated(global::LightSwitchApplication.NewInvoiceScreen s)
            {
                s.NewInvoiceScreen_Created();
            }
            private static void __NewInvoiceScreen_InvokeActivated(global::LightSwitchApplication.NewInvoiceScreen s)
            {
                s.NewInvoiceScreen_Activated();
            }
            private static bool __NewInvoiceScreen_InvokeSaveErrorEvent(global::LightSwitchApplication.NewInvoiceScreen s, global::System.Exception ex)
            {
                bool handled = false;
                s.NewInvoiceScreen_SaveError(ex, ref handled);
                return handled;
            }

            public DetailsClass() : base()
            {
            }

            public new global::LightSwitchApplication.NewInvoiceScreen.DetailsClass.PropertySet Properties
            {
                get
                {
                    return base.Properties;
                }
            }

            public new global::LightSwitchApplication.NewInvoiceScreen.DetailsClass.CommandSet Commands
            {
                get
                {
                    return base.Commands;
                }
            }

            public new global::LightSwitchApplication.NewInvoiceScreen.DetailsClass.MethodSet Methods
            {
                get
                {
                    return base.Methods;
                }
            }

            private global::Microsoft.LightSwitch.IDataServiceQueryable InvoiceDetailsQuery()
            {
                if (this.Screen.InvoiceProperty == null)
                {
                    return null;
                }

                global::Microsoft.LightSwitch.IDataServiceQueryable<global::LightSwitchApplication.InvoiceDetail> loader =
                    (global::Microsoft.LightSwitch.IDataServiceQueryable<global::LightSwitchApplication.InvoiceDetail>)((global::Microsoft.LightSwitch.Details.ILoadableProperty)this.Screen.InvoiceProperty.Details.Properties.InvoiceDetails).Loader;
                if (loader == null)
                {
                    return null;
                }

                return loader;
            }

            [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
            private global::Microsoft.LightSwitch.Details.Framework.Client.ScreenLocalProperty<global::LightSwitchApplication.NewInvoiceScreen, global::LightSwitchApplication.NewInvoiceScreen.DetailsClass, global::LightSwitchApplication.Invoice>.Data _InvoiceProperty;

            [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
            private global::Microsoft.LightSwitch.Details.Framework.Client.ScreenCollectionProperty<global::LightSwitchApplication.NewInvoiceScreen, global::LightSwitchApplication.NewInvoiceScreen.DetailsClass, global::LightSwitchApplication.InvoiceDetail>.Data _InvoiceDetails;

            [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "12.1.0.0")]
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public sealed class PropertySet
                : global::Microsoft.LightSwitch.Details.Framework.Client.ScreenPropertySet<global::LightSwitchApplication.NewInvoiceScreen, global::LightSwitchApplication.NewInvoiceScreen.DetailsClass>
            {

                public global::Microsoft.LightSwitch.Details.Framework.Client.ScreenLocalProperty<global::LightSwitchApplication.NewInvoiceScreen, global::LightSwitchApplication.NewInvoiceScreen.DetailsClass, global::LightSwitchApplication.Invoice> InvoiceProperty
                {
                    get
                    {
                        return (global::Microsoft.LightSwitch.Details.Framework.Client.ScreenLocalProperty<global::LightSwitchApplication.NewInvoiceScreen, global::LightSwitchApplication.NewInvoiceScreen.DetailsClass, global::LightSwitchApplication.Invoice>)base.GetItem(global::LightSwitchApplication.NewInvoiceScreen.DetailsClass.PropertySetProperties.InvoiceProperty);
                    }
                }

                public global::Microsoft.LightSwitch.Details.Framework.Client.ScreenCollectionProperty<global::LightSwitchApplication.NewInvoiceScreen, global::LightSwitchApplication.NewInvoiceScreen.DetailsClass, global::LightSwitchApplication.InvoiceDetail> InvoiceDetails
                {
                    get
                    {
                        return (global::Microsoft.LightSwitch.Details.Framework.Client.ScreenCollectionProperty<global::LightSwitchApplication.NewInvoiceScreen, global::LightSwitchApplication.NewInvoiceScreen.DetailsClass, global::LightSwitchApplication.InvoiceDetail>)base.GetItem(global::LightSwitchApplication.NewInvoiceScreen.DetailsClass.PropertySetProperties.InvoiceDetails);
                    }
                }

            }

            [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "12.1.0.0")]
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public sealed class CommandSet
                : global::Microsoft.LightSwitch.Details.Framework.Client.ScreenCommandSet<global::LightSwitchApplication.NewInvoiceScreen, global::LightSwitchApplication.NewInvoiceScreen.DetailsClass>
            {
            }

            [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "12.1.0.0")]
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public sealed class MethodSet
                : global::Microsoft.LightSwitch.Details.Framework.Client.ScreenMethodSet<global::LightSwitchApplication.NewInvoiceScreen, global::LightSwitchApplication.NewInvoiceScreen.DetailsClass>
            {
            }

            [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "12.1.0.0")]
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            internal sealed class PropertySetProperties
            {

                public static readonly global::Microsoft.LightSwitch.Details.Framework.Client.ScreenLocalProperty<global::LightSwitchApplication.NewInvoiceScreen, global::LightSwitchApplication.NewInvoiceScreen.DetailsClass, global::LightSwitchApplication.Invoice>.Entry
                    InvoiceProperty = new global::Microsoft.LightSwitch.Details.Framework.Client.ScreenLocalProperty<global::LightSwitchApplication.NewInvoiceScreen, global::LightSwitchApplication.NewInvoiceScreen.DetailsClass, global::LightSwitchApplication.Invoice>.Entry(
                        "InvoiceProperty",
                        false,
                        global::LightSwitchApplication.NewInvoiceScreen.DetailsClass.PropertySetProperties._InvoiceProperty_Stub,
                        global::LightSwitchApplication.NewInvoiceScreen.DetailsClass.PropertySetProperties._InvoiceProperty_Validate,
                        global::LightSwitchApplication.NewInvoiceScreen.DetailsClass.PropertySetProperties._InvoiceProperty_OnValueChanged);
                private static void _InvoiceProperty_Stub(global::Microsoft.LightSwitch.Details.Framework.Base.DetailsCallback<global::LightSwitchApplication.NewInvoiceScreen.DetailsClass, global::Microsoft.LightSwitch.Details.Framework.Client.ScreenLocalProperty<global::LightSwitchApplication.NewInvoiceScreen, global::LightSwitchApplication.NewInvoiceScreen.DetailsClass, global::LightSwitchApplication.Invoice>.Data> c, global::LightSwitchApplication.NewInvoiceScreen.DetailsClass d, object sf)
                {
                    c(d, ref d._InvoiceProperty, sf);
                }
                private static void _InvoiceProperty_Validate(global::LightSwitchApplication.NewInvoiceScreen s, global::Microsoft.LightSwitch.Framework.Client.ScreenValidationResultsBuilder r)
                {
                    s.InvoiceProperty_Validate(r);
                }
                private static void _InvoiceProperty_OnValueChanged(global::LightSwitchApplication.NewInvoiceScreen s)
                {
                    s.InvoiceProperty_Changed();
                }

                public static readonly global::Microsoft.LightSwitch.Details.Framework.Client.ScreenCollectionProperty<global::LightSwitchApplication.NewInvoiceScreen, global::LightSwitchApplication.NewInvoiceScreen.DetailsClass, global::LightSwitchApplication.InvoiceDetail>.Entry
                    InvoiceDetails = new global::Microsoft.LightSwitch.Details.Framework.Client.ScreenCollectionProperty<global::LightSwitchApplication.NewInvoiceScreen, global::LightSwitchApplication.NewInvoiceScreen.DetailsClass, global::LightSwitchApplication.InvoiceDetail>.Entry(
                        "InvoiceDetails",
                        global::LightSwitchApplication.NewInvoiceScreen.DetailsClass.PropertySetProperties._InvoiceDetails_Stub,
                        global::LightSwitchApplication.NewInvoiceScreen.DetailsClass.PropertySetProperties._InvoiceDetails_Validate,
                        global::LightSwitchApplication.NewInvoiceScreen.DetailsClass.PropertySetProperties._InvoiceDetails_CreateQuery,
                        global::LightSwitchApplication.NewInvoiceScreen.DetailsClass.PropertySetProperties._InvoiceDetails_SelectionChanged,
                        global::LightSwitchApplication.NewInvoiceScreen.DetailsClass.PropertySetProperties._InvoiceDetails_OnCollectionChanged,
                        global::LightSwitchApplication.NewInvoiceScreen.DetailsClass.PropertySetProperties._InvoiceDetails_OnLoaded);
                private static void _InvoiceDetails_Stub(global::Microsoft.LightSwitch.Details.Framework.Base.DetailsCallback<global::LightSwitchApplication.NewInvoiceScreen.DetailsClass, global::Microsoft.LightSwitch.Details.Framework.Client.ScreenCollectionProperty<global::LightSwitchApplication.NewInvoiceScreen, global::LightSwitchApplication.NewInvoiceScreen.DetailsClass, global::LightSwitchApplication.InvoiceDetail>.Data> c, global::LightSwitchApplication.NewInvoiceScreen.DetailsClass d, object sf)
                {
                    c(d, ref d._InvoiceDetails, sf);
                }
                private static void _InvoiceDetails_Validate(global::LightSwitchApplication.NewInvoiceScreen s, global::Microsoft.LightSwitch.Framework.Client.ScreenValidationResultsBuilder r)
                {
                    s.InvoiceDetails_Validate(r);
                }
                private static global::Microsoft.LightSwitch.IDataServiceQueryable _InvoiceDetails_CreateQuery(global::LightSwitchApplication.NewInvoiceScreen.DetailsClass d, object[] args)
                {
                    return d.InvoiceDetailsQuery();
                }
                private static void _InvoiceDetails_SelectionChanged(global::LightSwitchApplication.NewInvoiceScreen s)
                {
                    s.InvoiceDetails_SelectionChanged();
                }
                private static void _InvoiceDetails_OnCollectionChanged(global::LightSwitchApplication.NewInvoiceScreen s, global::System.Collections.Specialized.NotifyCollectionChangedEventArgs e)
                {
                    s.InvoiceDetails_Changed(e);
                }
                private static void _InvoiceDetails_OnLoaded(global::LightSwitchApplication.NewInvoiceScreen s, bool succeeded)
                {
                    s.InvoiceDetails_Loaded(succeeded);
                }

            }

            [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "12.1.0.0")]
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            internal sealed class CommandSetProperties
            {
            }

            [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "12.1.0.0")]
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            internal sealed class MethodSetProperties
            {
            }
        }
    }
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "12.1.0.0")]
    public sealed partial class PrintScreen
        : global::Microsoft.LightSwitch.Framework.Client.ScreenObject<global::LightSwitchApplication.PrintScreen, global::LightSwitchApplication.PrintScreen.DetailsClass>
    {
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "12.1.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        private PrintScreen() : base("LightSwitchApplication.Invoices.DesktopClient:PrintScreen")
        {
            global::LightSwitchApplication.PrintScreen.DetailsClass.Initialize(this);
        }

        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "12.1.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public static PrintScreen CreateInstance()
        {
            return new global::LightSwitchApplication.PrintScreen(
            );
        }

        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void PrintScreen_InitializeDataWorkspace(global::System.Collections.Generic.List<global::Microsoft.LightSwitch.IDataService> saveChangesTo);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void PrintScreen_Created();
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void PrintScreen_Activated();
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void PrintScreen_Saving(ref bool handled);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void PrintScreen_Saved();
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void PrintScreen_Closing(ref bool cancel);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void PrintScreen_SaveError(global::System.Exception exception, ref bool handled);
     
        #region Private Properties
        
        /// <summary>
        /// Gets the Application object for this application.  The Application object provides access to active screens, methods to open screens and access to the current user.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "12.1.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        private global::LightSwitchApplication.Application Application
        {
            get
            {
                return global::LightSwitchApplication.Application.Current;
            }
        }
        
        /// <summary>
        /// Gets the containing data workspace.  The data workspace provides access to all data sources in the application.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "12.1.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        private global::LightSwitchApplication.DataWorkspace DataWorkspace
        {
            get
            {
                return (global::LightSwitchApplication.DataWorkspace)((global::Microsoft.LightSwitch.Details.Client.IScreenDetails)this.Details).DataWorkspace;
            }
        }
        
        #endregion
 
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "12.1.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public sealed class DetailsClass
            : global::Microsoft.LightSwitch.Details.Framework.Client.ScreenDetails<global::LightSwitchApplication.PrintScreen, global::LightSwitchApplication.PrintScreen.DetailsClass, global::LightSwitchApplication.PrintScreen.DetailsClass.PropertySet, global::LightSwitchApplication.PrintScreen.DetailsClass.CommandSet, global::LightSwitchApplication.PrintScreen.DetailsClass.MethodSet>
        {

            static DetailsClass()
            {
            }

            [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
            private static global::Microsoft.LightSwitch.Details.Framework.Client.ScreenDetails<global::LightSwitchApplication.PrintScreen, global::LightSwitchApplication.PrintScreen.DetailsClass>.Entry
                __PrintScreenEntry = new global::Microsoft.LightSwitch.Details.Framework.Client.ScreenDetails<global::LightSwitchApplication.PrintScreen, global::LightSwitchApplication.PrintScreen.DetailsClass>.Entry(
                    global::LightSwitchApplication.PrintScreen.DetailsClass.__PrintScreen_InvokeInitializeDataWorkspace,
                    global::LightSwitchApplication.PrintScreen.DetailsClass.__PrintScreen_InvokeSavingEvent,
                    global::LightSwitchApplication.PrintScreen.DetailsClass.__PrintScreen_InvokeSavedEvent,
                    global::LightSwitchApplication.PrintScreen.DetailsClass.__PrintScreen_InvokeClosingEvent,
                    global::LightSwitchApplication.PrintScreen.DetailsClass.__PrintScreen_InvokeCreated,
                    global::LightSwitchApplication.PrintScreen.DetailsClass.__PrintScreen_InvokeActivated,
                    global::LightSwitchApplication.PrintScreen.DetailsClass.__PrintScreen_InvokeSaveErrorEvent);
            private static void __PrintScreen_InvokeInitializeDataWorkspace(global::LightSwitchApplication.PrintScreen s, global::System.Collections.Generic.List<global::Microsoft.LightSwitch.IDataService> saveChangesTo)
            {
                s.PrintScreen_InitializeDataWorkspace(saveChangesTo);
            }
            private static bool __PrintScreen_InvokeSavingEvent(global::LightSwitchApplication.PrintScreen s)
            {
                bool handled = false;
                s.PrintScreen_Saving(ref handled);
                return handled;
            }
            private static void __PrintScreen_InvokeSavedEvent(global::LightSwitchApplication.PrintScreen s)
            {
                s.PrintScreen_Saved();
            }
            private static bool __PrintScreen_InvokeClosingEvent(global::LightSwitchApplication.PrintScreen s)
            {
                bool cancel = false;
                s.PrintScreen_Closing(ref cancel);
                return cancel;
            }
            private static void __PrintScreen_InvokeCreated(global::LightSwitchApplication.PrintScreen s)
            {
                s.PrintScreen_Created();
            }
            private static void __PrintScreen_InvokeActivated(global::LightSwitchApplication.PrintScreen s)
            {
                s.PrintScreen_Activated();
            }
            private static bool __PrintScreen_InvokeSaveErrorEvent(global::LightSwitchApplication.PrintScreen s, global::System.Exception ex)
            {
                bool handled = false;
                s.PrintScreen_SaveError(ex, ref handled);
                return handled;
            }

            public DetailsClass() : base()
            {
            }

            public new global::LightSwitchApplication.PrintScreen.DetailsClass.PropertySet Properties
            {
                get
                {
                    return base.Properties;
                }
            }

            public new global::LightSwitchApplication.PrintScreen.DetailsClass.CommandSet Commands
            {
                get
                {
                    return base.Commands;
                }
            }

            public new global::LightSwitchApplication.PrintScreen.DetailsClass.MethodSet Methods
            {
                get
                {
                    return base.Methods;
                }
            }

            [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "12.1.0.0")]
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public sealed class PropertySet
                : global::Microsoft.LightSwitch.Details.Framework.Client.ScreenPropertySet<global::LightSwitchApplication.PrintScreen, global::LightSwitchApplication.PrintScreen.DetailsClass>
            {
            }

            [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "12.1.0.0")]
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public sealed class CommandSet
                : global::Microsoft.LightSwitch.Details.Framework.Client.ScreenCommandSet<global::LightSwitchApplication.PrintScreen, global::LightSwitchApplication.PrintScreen.DetailsClass>
            {
            }

            [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "12.1.0.0")]
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public sealed class MethodSet
                : global::Microsoft.LightSwitch.Details.Framework.Client.ScreenMethodSet<global::LightSwitchApplication.PrintScreen, global::LightSwitchApplication.PrintScreen.DetailsClass>
            {
            }

            [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "12.1.0.0")]
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            internal sealed class PropertySetProperties
            {
            }

            [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "12.1.0.0")]
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            internal sealed class CommandSetProperties
            {
            }

            [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "12.1.0.0")]
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            internal sealed class MethodSetProperties
            {
            }
        }
    }
}
